apiVersion: v2
name: spring-todo-app
description: A Helm chart for Spring Boot Todo Application
type: application
version: 0.1.0
appVersion: "1.0.0"

# 依赖 MySQL
dependencies:
  - name: mysql
    version: "9.0.0"
    repository: "https://charts.bitnami.com/bitnami"
    condition: mysql.enabled
    